config/routes.rb
Rails.application.routes.draw do
  get 'pages/info'
  resources :hospitals
  root to: redirect('/hospitals')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
	mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: [:show, :edit, :update, :destroy]

  # GET /hospitals
  # GET /hospitals.json
  def index
    @hospitals = Hospital.all
  end

  # GET /hospitals/1
  # GET /hospitals/1.json
  def show
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals
  # POST /hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to @hospital, notice: 'Hospital was successfully created.' }
        format.json { render :show, status: :created, location: @hospital }
      else
        format.html { render :new }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitals/1
  # PATCH/PUT /hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1
  # DELETE /hospitals/1.json
  def destroy
    @hospital.destroy
    respond_to do |format|
      format.html { redirect_to hospitals_url, notice: 'Hospital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hospital_params
      params.require(:hospital).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/hospitals/_form.html.erb
<%= form_with(model: hospital, local: true) do |form| %>
  <% if hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
      <% hospital.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hospitals/edit.html.erb
<h1>Editing Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Show', @hospital %> |
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hospitals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hospitals.each do |hospital| %>
      <tr>
        <td><%= hospital.name %></td>
        <td><%= hospital.description %></td>
        <td><%= image_tag idea.picture_url, width: '100%' if idea.picture.present? %></td>
        <td><%= link_to 'Show', hospital %></td>
        <td><%= link_to 'Edit', edit_hospital_path(hospital) %></td>
        <td><%= link_to 'Destroy', hospital, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hospital', new_hospital_path %>

app/views/hospitals/new.html.erb
<h1>New Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Back', hospitals_path %>

app/views/hospitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hospital.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hospital.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @hospital.picture %>
</p>

<%= link_to 'Edit', edit_hospital_path(@hospital) %> |
<%= link_to 'Back', hospitals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Val</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="/">The Idea App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/hospitals">hospitals</a>
        </li>
        <li class="nav-item">
  <a class="nav-link" href="/pages/info">Info</a>
</li>
      </ul>
    </div>
  </div>
</nav>
    <div class="container">
  <%= yield %>
</div>
<footer>
  <div class="container">
    valentine gatwiri <%= Time.now.year %>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in facebook https://web.facebook.com/valentine.gatwiri.5</p>
<p>twitter https://twitter.com/ValentineGatwi2</p>